plugins:
  - node
extends:
  - "eslint:recommended"
  - "plugin:node/recommended"
rules:
  semi: [2, "never"]
  "node/exports-style":
    - "error"
    - "module.exports"
  "node/no-unpublished-bin": "error"
  "node/process-exit-as-throw": "error"
